---
- name: Deploiement de gatsby sur un serveur Apache 
  hosts: ec2  #cibles où l'application Gatsby sera déployée
  become: true
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Installation de Git
      ansible.builtin.package:
        name: git
        state: present

    - name: Clonage du dépot github contenant l'application Gatsby
      ansible.builtin.git:
        repo: https://github.com/gatsbyjs/gatsby-starter-default
        dest: ./gatsby-cli
        update: yes #met à jour le dépôt si existant
    
    - name: Installation des dépendances
      ansible.builtin.command:
        cmd: npm install
      args:
        chdir: ./gatsby-cli

    - name: Construction de l'application gatsby
      ansible.builtin.command:
        cmd: npm run build
      args:
        chdir: ./gatsby-cli

    